name: Generate Snake

on:
  schedule:                # Executa automaticamente a cada 24h
    - cron: "0 0 * * *"
  workflow_dispatch:       # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: generoso28
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch de saída
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
